# Generated by Django 2.1.7 on 2019-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expected_salery', models.IntegerField()),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('nationality', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('birth', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posting_title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('Internship_discription', models.TextField()),
                ('Location', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.CharField(max_length=50)),
            ],
        ),
    ]
